In [21]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [22]:
train=pd.read_csv("set1.csv")
test=pd.read_csv("set2.csv")

trainset=np.array(train.values)
testset=np.array(test.values)

Xtrain, ytrain=trainset[:, :trainset.shape[1]-1], trainset[:, trainset.shape[1]-1:]
Xtest, ytest=testset[:, :testset.shape[1]-1], testset[:, trainset.shape[1]-1:]

X_train=Xtrain.reshape(Xtrain.shape[0], 28, 28)
X_test=Xtest.reshape(Xtest.shape[0], 28, 28)

In [23]:
y_train=ytrain.reshape(ytrain.shape[0])
y_test=ytest.reshape(ytest.shape[0])

In [24]:
X_test=X_test/255.0
X_train=X_train/255.0

In [25]:
from sklearn.ensemble import ExtraTreesClassifier
clf=ExtraTreesClassifier(n_estimators=50, max_features=50)

In [26]:
X_train=X_train.reshape(X_train.shape[0],X_train.shape[1]*X_train.shape[2])
X_test=X_test.reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2])

In [27]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [28]:
clf=clf.fit(X_train,y_train)

In [29]:
y_pred=clf.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
print("Accuracy", acc*100)

('Accuracy', 100.0)


In [31]:
y_in=clf.predict_proba(X_train)
y_out=clf.predict_proba(X_test)

In [32]:
print(y_in[10:15])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [33]:
import pandas as pd
import numpy as np

In [35]:
din=np.hstack((y_in, np.ones((y_in.shape[0],1))))
dout=np.hstack((y_out, np.zeros((y_out.shape[0],1))))
dt=np.vstack((din,dout))
df=pd.DataFrame(dt)
df.to_csv("sh_forest.csv", index=False, header=True)